version: '2'

services:
    workspace:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
            - .:/usr/src/app
        ports:
            - 3449:3449
            - 7888:7888
        command: ["/usr/src/app/ui/run.sh"]
           
